[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/rayzor-blade/xwindow"
license = "MIT"

[workspace.dependencies]
xwindow-core = { path = "crates/xwindow-core" }
x_idl = { git = "https://github.com/rayzor-blade/x-idl.git", rev = "bf1ab2f262c00438f26e261a45822e3fbd6db76a" }
