[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/rayzor-blade/xwindow"
license = "MIT"

[workspace.dependencies]
xwindow-core = { path = "crates/xwindow-core" }
x_idl = { git = "https://github.com/rayzor-blade/x-idl.git", rev = "3435b2905e1804712f3d1b8addfbeb6ee876048f" }
